apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings-xml
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
        <mirrors>
            <mirror>
                <id>my-maven-central</id>
                <name>EA Lab Nexus Maven Central</name>
                <url>https://your.nexus.url/</url>
                <mirrorOf>*</mirrorOf>
            </mirror>
        </mirrors>
    </settings>
